#include "ft_printf.h"
#include <stdio.h>

int	main(void)
{
	int i;
	i = 0;
	printf("\n"); printf("%65s ", "........................................................"); printf("\n");
						printf("%43s%-8s ", "NormalMode", ""); printf("\n");
	printf("%65s ", "........................................................"); printf("\n"); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%d");		i = printf("%d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%3d");		i = printf("%3d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%8d");		i = printf("%8d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%.d");		i = printf("%.d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%.2d");		i = printf("%.2d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%.8d");		i = printf("%.8d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%d");		i = printf("%d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%3d");		i = printf("%3d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%8d");		i = printf("%8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%.d");		i = printf("%.d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%.2d");		i = printf("%.2d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%.8d");		i = printf("%.8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%0d");		i = printf("%0d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%03d");		i = printf("%03d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%08d");		i = printf("%08d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%0.d");		i = printf("%0.d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%0.2d");	i = printf("%0.2d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%0.8d");	i = printf("%0.8d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%0d");		i = printf("%0d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%03d");		i = printf("%03d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%08d");		i = printf("%08d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%0.d");		i = printf("%0.d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%0.2d");		i = printf("%0.2d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%0.8d");		i = printf("%0.8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");

	printf("\n"); printf("%65s ", "........................................................"); printf("\n");
						printf("%43s%-8s ", "LeftMode", ""); printf("\n");
	printf("%65s ", "........................................................"); printf("\n"); printf("\n");

	printf("%21s%5s%-8s|", "hell", "", "%-d");			i = printf("%-d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-3d");			i = printf("%-3d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-8d");			i = printf("%-8d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-.d");			i = printf("%-.d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-.2d");		i = printf("%-.2d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-.8d");		i = printf("%-.8d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-d");			i = printf("%-d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-3d");			i = printf("%-3d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-8d");			i = printf("%-8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-.d");			i = printf("%-.d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-.2d");			i = printf("%-.2d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-.8d");			i = printf("%-.8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-0d");			i = printf("%-0d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-03d");		i = printf("%-03d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-08d");		i = printf("%-08d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-0.d");		i = printf("%-0.d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-0.2d");		i = printf("%-0.2d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%-0.8d");		i = printf("%-0.8d", 2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-0d");			i = printf("%-0d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-03d");			i = printf("%-03d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-08d");			i = printf("%-08d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-0.d");			i = printf("%-0.d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-0.2d");		i = printf("%-0.2d", 0);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-0.8d");		i = printf("%-0.8d", 0);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");

	printf("\n"); printf("%65s ", "........................................................"); printf("\n");
						printf("%43s%-8s ", "MixNormalMode", ""); printf("\n");
	printf("%65s ", "........................................................"); printf("\n"); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%8.d");			i = printf("%8.d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%8.3d");		i = printf("%8.3d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%8.3d");		i = printf("%8.6d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%3.2d");		i = printf("%3.2d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%3.8d");		i = printf("%3.8d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%6.8d");		i = printf("%6.8d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%8.d");			i = printf("%8.d", 0);			printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%8.3d");			i = printf("%8.3d", 0);			printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%8.6d");			i = printf("%8.6d", 0);			printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%3.2d");			i = printf("%3.2d", 0);			printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%3.8d");			i = printf("%3.8d", 0);			printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%6.8d");			i = printf("%6.8d", 0);			printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-8.d");		i = printf("%08.d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-8.3d");		i = printf("%08.3d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-8.6d");		i = printf("%08.6d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-3.2d");		i = printf("%03.2d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-3.8d");		i = printf("%03.8d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-6.8d");		i = printf("%06.8d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%8.d");			i = printf("%-8.d", 0);			printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%8.3d");			i = printf("%-8.3d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%8.6d");			i = printf("%-8.6d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%3.2d");			i = printf("%-3.2d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%3.8d");			i = printf("%-3.8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%6.8d");			i = printf("%-6.8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-8.d");		i = printf("%-8.d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-8.3d");		i = printf("%-8.3d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-8.6d");		i = printf("%-8.6d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-3.2d");		i = printf("%-3.2d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-3.8d");		i = printf("%-3.8d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-6.8d");		i = printf("%-6.8d", 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%0d");			i = printf("%*f", 8, 2718);				printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%03d");			i = printf("%*.*d", 8, 3, 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%08d");			i = printf("%*.*d", 8, 6, 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%0.d");			i = printf("%*.*d", 8, 6, 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%0.2d");		i = printf("%*.*d", 3, 2, 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%0.8d");		i = printf("%*.*d", 3, 8, 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "hell", "", "%0.8d");		i = printf("%*.*d", 6, 8, 2718);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");

		printf("\n"); printf("%65s ", "........................................................"); printf("\n");
						printf("%43s%-8s ", "NormaNegativelMode", ""); printf("\n");
	printf("%65s ", "........................................................"); printf("\n"); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%d");		i = printf("%d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%3d");		i = printf("%3d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%8d");		i = printf("%8d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%.d");		i = printf("%.d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%.2d");		i = printf("%.2d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%.8d");		i = printf("%.8d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%d");		i = printf("%d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%3d");		i = printf("%3d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%8d");		i = printf("%8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%.d");		i = printf("%.d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%.2d");		i = printf("%.2d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%.8d");		i = printf("%.8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%0d");		i = printf("%0d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%03d");		i = printf("%03d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%08d");		i = printf("%08d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%0.d");		i = printf("%0.d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%0.2d");	i = printf("%0.2d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%0.8d");	i = printf("%0.8d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%0d");		i = printf("%0d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%03d");		i = printf("%03d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%08d");		i = printf("%08d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%0.d");		i = printf("%0.d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%0.2d");		i = printf("%0.2d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%0.8d");		i = printf("%0.8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");

	printf("\n"); printf("%65s ", "........................................................"); printf("\n");
						printf("%43s%-8s ", "LeftNegativeMode", ""); printf("\n");
	printf("%65s ", "........................................................"); printf("\n"); printf("\n");

	printf("%21s%5s%-8s|", "2718", "", "%-d");			i = printf("%-d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-3d");			i = printf("%-3d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-8d");			i = printf("%-8d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-.d");			i = printf("%-.d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-.2d");		i = printf("%-.2d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-.8d");		i = printf("%-.8d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-d");			i = printf("%-d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-3d");			i = printf("%-3d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-8d");			i = printf("%-8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-.d");			i = printf("%-.d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-.2d");			i = printf("%-.2d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-.8d");			i = printf("%-.8d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-0d");			i = printf("%-0d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-03d");		i = printf("%-03d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-08d");		i = printf("%-08d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-0.d");		i = printf("%-0.d", -2718);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-0.2d");		i = printf("%-0.2d", -2718);printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "2718", "", "%-0.8d");		i = printf("%-0.8d", -2718);printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-0d");			i = printf("%-0d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-03d");			i = printf("%-03d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-08d");			i = printf("%-08d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-0.d");			i = printf("%-0.d", 0);		printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-0.2d");		i = printf("%-0.2d", 0);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("%21s%5s%-8s|", "0  ", "", "%-0.8d");		i = printf("%-0.8d", 0);	printf("%s\t:%d:", "|", i); printf("\n");
	printf("\n");

	// printf("-->|%-16.p|<-- ", 0);
	// printf("\n");
	// ft_printf("-->|%-16.p|<-- ", NULL);
	// printf("\n");
	return (0);
}
